### ISSUE TITLE
Include note on the README that kicker doesn't work with non-system ruby?

### ISSUE THREAD

**Issue by timcharper** [alloy/kicker#14]
I can't get it to work with my RVM installed ruby-1.8.7.  Should it be working?  (seems like no since I am getting a ruby-cocoa require failure)

```
/Users/timcharper/Developer/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- osx/cocoa (LoadError)
        from /Users/timcharper/Developer/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /Users/timcharper/Developer/.rvm/gems/ruby-1.8.7-p334/gems/kicker-2.3.0/vendor/rucola/fsevents.rb:1
        from /Users/timcharper/Developer/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /Users/timcharper/Developer/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /Users/timcharper/Developer/.rvm/gems/ruby-1.8.7-p334/gems/kicker-2.3.0/lib/kicker.rb:2
        from /Users/timcharper/Developer/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from /Users/timcharper/Developer/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from /Users/timcharper/Developer/.rvm/gems/ruby-1.8.7-p334/gems/kicker-2.3.0/bin/kicker:4
        from /Users/timcharper/Developer/.rvm/gems/ruby-1.8.7-p334/bin/kicker:19:in `load'
        from /Users/timcharper/Developer/.rvm/gems/ruby-1.8.7-p334/bin/kicker:19
```

**Comment by timcharper** [comment]
Maybe even a post_install_message? I can send a pull request if you confirm to me that kicker is only intended to work with system ruby.

**Comment by alloy** [comment]
Well, actually the problem is that if you install your own Ruby you will also have to install RubyCocoa from source. However, like discussed in the other tickets, the proper solution is to add a C ext which would make it work on all MRI rubies.
